### PR TITLE
Update Neb_Instr_Tester.zip

### PR DESCRIPTION
**Pull request by Airell**
Small change to 'conductor.py' to make .wav's load on Windows

 4: import sys
81: if sys.platform.startswith('win'):
82:  f = f.replace("\\","/")  #For Windows paths

### CODE REVIEW

**Comment by stephenhensley** [comment]
@Airell thanks for the contribution!

It appears that you pushed the changes as a .zip file instead of the changed files.

Happy to take a look if you push the file changes directly.

**Comment by Airell** [comment]
Correct, but you also provide it as a zip. I changed the file only in this zip.
There is a source version available in 'Code\instr_tester', but it's older than the source in the zip and I think it should reflect what is in the zip.

**Comment by Airell** [comment]
Added the single conductor.py file

**Comment by stephenhensley** [comment]
Change applied in #25, and source code updated to last real version (used to create the .zip file version)

**Pull request closed without merging**
