### PR TITLE
Alternate instrument AVALON

### PR DESCRIPTION
**Pull request by Airell**
AVALON is a Morphing Terrarium E350 inspired instrument which can read Cloud Terrarium E352 wavetable files. It can morph the wavetables in a XY 8x8 grid as well as Z morphing through all 64 waves. As an extra it can also morph between the XY and Z waves in a couple of different modes.

### CODE REVIEW

**Comment by pmsorhaindo** [comment]
OMG this sounds amazing, will try it out this weekend!

**Comment by Airell** [comment]
@pmsorhaindo thanks! I have been working on a newer version (just commited it), adding some nice additions:
- Two up/down extra oscillators, with detuning
- 'No Morphing', which will make you select 'clean' waveforms (Blend still blend XY and Z)
- Adding a WaveEdit .wav file, specially selected for Avalon to start playing with

**Comment by pmsorhaindo** [comment]
Minus the pitch issues this is really really really good!!!

**Comment by Airell** [comment]
And what kind of pitch issues are you experiencing?
If it's 1v/octave tracking, than it's the Neb itself. Check https://github.com/Qu-Bit-Electronix/QB_Nebulae_V2/issues/24 which addresses a fix for 1v/octave tracking. There is a file attached (testC.zip) which outputs a simple 'C' sine, please check if that does track 1v/oct...
Also the very slight 'slew' between notes is something I can not change.
There is no 1v/oct magic and no slewing at all implemented in the .instr.

**Comment by pmsorhaindo** [comment]
Yeah, you're quite right it's not this instrument's issue. 👍🏾

**Pull request merged**
