### PR TITLE
Scale fixes

### PR DESCRIPTION
**Pull request by CorvusPrudens**
Fixed all instances of the scale opcode whose operands were backwards (largest value should come first). The only instances of scales _not_ being in the incorrect configuration was in the Risset Harmonic Oscillator instrument, so I didn't touch those. 

Since I don't really know how each individual instrument works, it's possible some of the scales shouldn't be reversed. That will have to be reviewed.

### CODE REVIEW

**Comment by Airell** [comment]
This looks like a fix for something I email Qu-Bit about a coule of months ago:

_"Some instruments (e.g. Wave Terrain and GENDYN), the have their 1v/oct 'inverted', but also Density and Overlap have 'opposite' responses. When turning the Pitch knob or playing from a keyboard, the pitch response is opposite from what it should be. The high notes are on the right, the low notes are on the left."_

Would this be the issue you fixed?

**Comment by stephenhensley** [comment]
@Airell This PR definitely addresses that issue. 

We can give them a quick test to make sure they match what they should, but all the uses of `scale` look like they're going the correct directions now. Thanks!

**Comment by CorvusPrudens** [comment]
Here's a list of all the modules that have changes and should be tested:

- [ ] Bowed Drone
- [ ] Comb Warp
- [ ] Drip Water
- [ ] FM Grit
- [ ] Four Osc
- [ ] Fractal Crust
- [ ] GENDYN
- [ ] Morphing FM
- [ ] Plucked Patterns
- [ ] Vinyl Dust
- [ ] Wave Terrain

**Comment by pmsorhaindo** [comment]
Would love to help out with testing the PR if I can be of any help. Will try and take a look this weekend.

**Comment by pmsorhaindo** [comment]
So I had a little play with the first 5 instruments this evening, would want to take more time testing stuff and play around with a few of the original versions of these instruments as some of them I only checked out so long ago I don't remember precisely how they functioned.

Bowed drone - responds to v/oct great, works as expected.
Comb Warp - I need a little more time to look at whether or not this instrument responds to v/oct in a meaningful way.
Drip Water - I don't think this instrument responds to v/oct. Appears to work fine though.
FM Grit - responds to v/oct great, works as expected.
Four Osc - v/oct doesn't appear to impact this instrument at all, although I suspect this was always the case (need to double check against original instruments code.
Fractal Crust - Although no information is present on the cheatsheet for v/oct control. The v/oct CV input appears to impact in the filter in a way that more high frequencies come through when higher cv is provided.
GENDYN - Appears to respond to work great v/oct response is as expected.
Morphing FM - Appears to work great v/oct response is as expected.
Plucked Patterns - Appears to work great v/oct response is as expected.
Vinyl Dust - no obvious change .instr doesn't appear to respond to v/oct CV.
Wave Terrain - Appears to work great v/oct response is as expected.

Also @Airell , Thanks so much for the Mars Affects instrument, I've been having tonnes of fun with it! :D

**Comment by Airell** [comment]
@pmsorhaindo Thanks! I hope it will become more official when it's added to: https://www.qubitelectronix.com/alternate-instruments
If you find any issues, let me know. In a previous version I had some issues with longer delays/reverbs which I hopefully fixed.

**Comment by stephenhensley** [comment]
@pmsorhaindo Thanks for being so thorough, and taking the time to test all of the instruments! 

@Airell The Mars Affects instrument will certainly make its way to the site soon. 😄

**Comment by pmsorhaindo** [comment]
@stephenhensley no sweat happy to try things out. I hope to contribute instruments myself some day soon.

**Comment by andrewikenberry** [comment]
Looks good!
Thanks again for contributing, testing, and making the Nebulae community a better place!

**Pull request merged**
